import { MetadataRoute } from "next";

const routes: MetadataRoute.Sitemap = [
  { url: "https://gitvision.dev", lastModified: new Date(), changeFrequency: "daily", priority: 1 },
  { url: "https://gitvision.dev/playground", lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
  { url: "https://gitvision.dev/learn", lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
  { url: "https://gitvision.dev/docs", lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
  { url: "https://gitvision.dev/linux-basics", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
  { url: "https://gitvision.dev/merge-conflicts", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
  { url: "https://gitvision.dev/internals", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
  { url: "https://gitvision.dev/classroom", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/blog", lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
  { url: "https://gitvision.dev/docs/git-init", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-add", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-commit", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-branch", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-merge", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-rebase", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-push", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-pull", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-status", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-diff", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-log", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-clone", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-checkout", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-switch", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-reset", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-stash", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-remote", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-fetch", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-revert", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-restore", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-tag", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/docs/git-reflog", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-show", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-blame", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-cherry-pick", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-bisect", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-worktree", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-submodule", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-gc", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-fsck", lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
  { url: "https://gitvision.dev/docs/git-config", lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  { url: "https://gitvision.dev/commands", lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
  { url: "https://gitvision.dev/404", lastModified: new Date(), changeFrequency: "never", priority: 0.1 },
];

export default function sitemap() {
  return routes;
}